spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://60.205.209.65:3306/gulimall-file?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 500000
  cloud:
    nacos:
      discovery:
        server-addr: 60.205.209.65:8848

  thymeleaf:
    cache: false # 关闭页面缓存
    encoding: UTF-8 # 模板编码
    prefix: classpath:/static/  # 页面映射路径
    suffix: .html # 试图后的后缀
    mode: HTML5 # 模板模式
  servlet:
    multipart:
      enabled: false
img:
  path: /mydata/nginx/html/image/